services:
  web_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  requests_app:
    build:
      context: ./requests_app
      dockerfile: Dockerfile
    depends_on:
      - web_app
    volumes:
      - ./requests_app:/requests_app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning


