global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: 'xxxxxxx'
        chat_id: xxxxx
        message: |
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} 
            *Description:* {{ .Annotations.description }} 
            *Status:* {{ .Status }} 
            *Starts At:* {{ .StartsAt }}
          {{ end }}

