global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'flask'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web_app:5000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert_rules.yml 
